#!/bin/bash
# Start a Clojure REPL with a configured classpath and working directory.

# Configuration
CONF=.clojure-repl.conf
CLASSPATH_FILE=.classpath
VERBOSE=
WORKING_DIR_MARKER=

# System paths
BASENAME=/usr/bin/basename
CAT=/bin/cat
DIRNAME=/usr/bin/dirname
FIND=/usr/bin/find
GETOPT=/usr/bin/getopt
GREP=/bin/grep
JAVA=/usr/bin/java
SORT=/usr/bin/sort
TAIL=/usr/bin/tail

# Override defaults in $CONF
[[ -f $HOME/$CONF ]] && . "$HOME/$CONF"

me=$($BASENAME $0)

function usage {
    echo "Start a Clojure REPL with a configured classpath and (if desired) a configured working directory.
    
    Usage: $me [-c | --classpath-file] [-h | --help] [-s | --sample-conf] [-v | --verbose] [-w | --working-dir-marker]
    -c|--classpath-file      Name of the file containing the complete classpath (Default: .classpath)
			     $me will look for your configured classpath file
			     starting in \$PWD and walking up to /. If no
			     classpath file is found, $me will look for
			     a Clojure .jar file under ~/.m2/ and use the latest
			     version found.
    -h|--help                Print this help message.
    -s|--sample-conf         Print a sample ~/$CONF file.
    -v|--verbose             Print some stuff on STDERR.
    -w|--working-dir-marker  Name of the file marking the REPL working dir (Default: unset)
                             $me will look for this marker file starting in
			     \$PWD and walking up to /. If the marker file is
			     unset or not found, \$PWD is not changed.

    Defaults can be overwritten in ~/$CONF.


    Here are a couple ways you might use $me
        $ lein classpath > .classpath
        $ $me

	# Or to use with Emacs inferior lisp, add this to your Emacs config:
        (setq clojure-inf-lisp-command \"$me\")

	Alternatively, see this pleasing elisp that starts a clojure-repl in
	a new buffer for you:
        https://gist.github.com/dzaharee/257476c8ecdf69a471f9
"
}

function confsample {
    echo "\
# Name of the file containing the complete classpath
CLASSPATH_FILE=.classpath

# Set to 1 to enable verbosity.
VERBOSE=

# Name of the file marking the REPL working dir
WORKING_DIR_MARKER= # empty for \$PWD

# The following system paths may also be overridden here:
#BASENAME=/usr/bin/basename
#CAT=/bin/cat
#DIRNAME=/usr/bin/dirname
#FIND=/usr/bin/find
#GETOPT=/usr/bin/getopt
#GREP=/bin/grep
#JAVA=/usr/bin/java
#SORT=/usr/bin/sort
#TAIL=/usr/bin/tail
"
}

TEMP=`$GETOPT -o c:,h,s,v,w: --long classpath-file:,help,sample-conf,verbose,working-dir-marker: -- "$@"`
if [ $? != 0 ] ; then echo "bad getopt exit" >&2 ; exit 1 ; fi
eval set -- "$TEMP"
while true ; do
    case "$1" in
        -c|--classpath-file) CLASSPATH_FILE=$2; shift 2 ;;
        -h|--help) usage; exit 0 ;;
	-s|--sample-conf) confsample; exit 0 ;;
	-v|--verbose) VERBOSE=1; shift ;;
        -w|--working-dir-marker) WORKING_DIR_MARKER=$2; shift 2 ;;
	--) shift ; break ;;
    esac
done

# Walk from $PWD up to /, looking for the file named in $1.
# If found, echo its path for capture.
function find_file {
    local target_file="$1"
    local d="$PWD"
    while [[ "/" != $(command cd -P $d && \pwd) ]]; do
        if [[ -f $d/$target_file ]]; then
	    if [[ -n $VERBOSE ]]; then
		>&2 echo "$target_file found! ($d/$target_file)"
	    fi
            echo "$d/$target_file"
            break
        fi
        d="$d/.."
    done
}

function find_cat_file {
    f=$(find_file $1)
    if [[ -n $f ]]; then
        $CAT "$f"
    fi
}

# Find the latest (sort -n) version of the clojure .jar in ~/.m2.
function find_clojure_jar {
    $FIND ~/.m2 -name clojure*.jar | $GREP org/clojure/clojure/ | $SORT -n | $TAIL -n1
}

# Put the classpath on stdout for capture.
function get_classpath {
    if [[ -n $VERBOSE ]]; then
	>&2 echo "Searching for \$CLASSPATH_FILE ($CLASSPATH_FILE)"
    fi
    classpath="$(find_cat_file $CLASSPATH_FILE)"
    if [[ -z $classpath ]]; then
        classpath="$(find_clojure_jar)"
        >&2 echo
        >&2 echo "WARNING: No $CLASSPATH_FILE found, resorting to $classpath."
        >&2 echo "         You may use 'lein classpath > $CLASSPATH_FILE' or 'cmma classpath > $CLASSPATH_FILE' to make a $CLASSPATH_FILE file for your project."
        >&2 echo
    fi
    echo "$classpath"
}

function change_working_dir {
    if [[ -n $WORKING_DIR_MARKER ]]; then
	if [[ -n $VERBOSE ]]; then
	    >&2 echo "Searching for \$WORKING_DIR_MARKER ($WORKING_DIR_MARKER)"
	fi
	d=$(find_file "$WORKING_DIR_MARKER")
	if [[ -n $d ]]; then
	    d=$($DIRNAME $d)
	    cd "$d"
	    if [[ -n $VERBOSE ]]; then
		>&2 echo PWD: $PWD
	    fi
	fi
    fi
}

###############################
CLASSPATH="$(get_classpath)"
if [[ -z $CLASSPATH ]]; then
    >&2 echo "No $CLASSPATH_FILE or Clojure .jar under ~/.m2/ found. Quitting in disgrace. :("
    exit 2
fi

change_working_dir

if [[ -n $VERBOSE ]]; then
    >&2 echo Starting clojure.main...
fi
$JAVA -cp "$CLASSPATH" clojure.main -r
