#!/usr/bin/env bash

set -x

xrandr --query
xrandr --auto
# might need to pick a different name for the mode, when calling --newmode
xrandr --newmode $(gtf 1920 1080 60 | grep Modeline | sed 's/^ *Modeline //' | sed 's/"/baka/g')
xrandr --addmode eDP-1 baka1920x1080_60.00baka
xrandr --output eDP-1 --mode baka1920x1080_60.00baka --dpi 144
xrandr --output HDMI-1 --right-of eDP-1
#xrandr --output DP-1-3 --right-of eDP-1 # try adding a "--mirror" mode setting before this one?
