#!/usr/bin/env bash

set -e
if [ "$DEBUG" ]; then set -x; fi

URI=${URI:-http://www.google.com}
LOGFILE=${LOGFILE:-~/.internet-monitoring.log}

CURL=${CURL:-/usr/bin/curl}
GREP=${GREP:-/bin/grep}

status=
if $CURL --head -s $URI | $GREP "HTTP/1.1 200 OK" >& /dev/null; then
    status=up
else
    status=down
fi

(echo -n "$status "; date) >> $LOGFILE
