#!/bin/bash
# Create a symlink from the name of your database to this file, and you can use
# the name of your database as an abbreviation for "psql etc. etc.
# your_database".
# E.g.:
# $ ln -s pggo my_fancy_db
# $ echo "select 1" | my_fancy_db

function usage {
    echo "Usage: " $(basename $0) " [-h | --help] [-c | --csv] [-- <psql options>]
    -h|--help Print this help message.
    -c|--csv  Output CSV from psql by wrapping STDIN with \"COPY (<STDIN>) TO STDOUT WITH CSV HEADER\"
              --csv will break if you input more than one SQL command.
    Use -- to separate options for this script and options for psql.
    "
}

db=`basename $0`
dbu=$db

# If the DB name has "test" in it, assume the DB user's name is "test".
[[ $db != ${db/test//} ]] && dbu=test

TEMP=`getopt -o c,h --long csv,help -- "$@"`
if [ $? != 0 ] ; then echo "bad getopt exit" >&2 ; exit 1 ; fi
eval set -- "$TEMP"
while true ; do
    case "$1" in
        -c|--csv) opt_csv=true; shift 1 ;;
        -h|--help) usage; exit 0 ;;
        --) shift ; break ;;
        *) echo "Internal error!" ; exit 1 ;;
    esac
done

prefix=
suffix=
if [ "$opt_csv" = true ]; then
    prefix="COPY ("
    suffix=") TO STDOUT WITH CSV HEADER"
fi

if [ -t 0 ]; then
    psql -U $dbu -E $db $*
else
    (echo "$prefix"; cat; echo "$suffix") | psql -U $dbu -E $db $*
fi
