#!/bin/bash
# Start a short-term Web server in the current directory.
# Port number may be specified, defaults to 8888.

port=$1

[[ -z "$port" ]] && echo "missing port number, defaulting to 8888" && port=8888

python -m SimpleHTTPServer $port
