#!/usr/bin/env bash
# Start a short-term Web server in the current directory.
# Port number may be specified, defaults to 8888.

port=$1

if [ ! "$port" ]; then
    echo "missing port number, defaulting to 8888"
    port=8888
fi

python -m SimpleHTTPServer $port || python -m http.server $port
